<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-4TF1D5V" name="week4.testng.groups.homework.MergeLead" tests="1" failures="0" timestamp="16 Sep 2017 12:24:17 GMT" time="19.926" errors="1">
  <testcase name="MergeLeadAtTest" time="19.926" classname="week4.testng.groups.homework.MergeLead">
    <error type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException
	at wrappers.GenericWrappers.clickByXpathNoSnap(GenericWrappers.java:310)
	at week4.testng.groups.homework.MergeLead.MergeLeadAtTest(MergeLead.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- MergeLeadAtTest -->
</testsuite> <!-- week4.testng.groups.homework.MergeLead -->
